In [1]:
import torch
import numpy as np
print(torch.__version__)

1.13.0+cu117


## Creating Tensors

In [7]:
# scaler is a zero dimensional tensor 
scaler = torch.tensor(3) 
scaler,scaler.ndim,scaler.item()

(tensor(3), 0, 3)

In [17]:
# vectors is one dimensional tensor 
vector = torch.tensor([13,2,95,3])
vector,vector.ndim,vector.shape # one dimensional vector with 4 elements inside

(tensor([13,  2, 95,  3]), 1, torch.Size([4]))

In [19]:
matrix = torch.tensor([[1,3,5,8],[139,498,285,877]])
matrix,matrix.ndim,matrix.shape

(tensor([[  1,   3,   5,   8],
         [139, 498, 285, 877]]),
 2,
 torch.Size([2, 4]))

In [24]:
tensor = torch.tensor([[[1,39,85],[99,94,92],[989,485,847],[848,32,12]]])
tensor,tensor.ndim,tensor.shape

(tensor([[[  1,  39,  85],
          [ 99,  94,  92],
          [989, 485, 847],
          [848,  32,  12]]]),
 3,
 torch.Size([1, 4, 3]))

In [28]:
random_tensor = torch.rand(size=(2,6,4))
random_tensor

tensor([[[0.5724, 0.7703, 0.8459, 0.6550],
         [0.4395, 0.3510, 0.2512, 0.4054],
         [0.2212, 0.9766, 0.2224, 0.8548],
         [0.8372, 0.8106, 0.7568, 0.6496],
         [0.6992, 0.1917, 0.3436, 0.1542],
         [0.2340, 0.3800, 0.0886, 0.1680]],

        [[0.4366, 0.6757, 0.8636, 0.9165],
         [0.7436, 0.5083, 0.1266, 0.3362],
         [0.6353, 0.9030, 0.9316, 0.3925],
         [0.9363, 0.4024, 0.1767, 0.2075],
         [0.5795, 0.0774, 0.9808, 0.5687],
         [0.0949, 0.3656, 0.2637, 0.4694]]])

In [34]:
random_tensor.shape,random_tensor.size(),random_tensor.dtype

(torch.Size([2, 6, 4]), torch.Size([2, 6, 4]), torch.float32)

In [35]:
random_image_tensor = torch.rand(size = (3,224,224))

In [36]:
random_image_tensor

tensor([[[0.2874, 0.5395, 0.0877,  ..., 0.4452, 0.7237, 0.8267],
         [0.3717, 0.6723, 0.0625,  ..., 0.8563, 0.6390, 0.3849],
         [0.9793, 0.6225, 0.0496,  ..., 0.4885, 0.8874, 0.0364],
         ...,
         [0.5973, 0.2907, 0.1087,  ..., 0.7633, 0.1053, 0.9919],
         [0.0689, 0.6418, 0.7524,  ..., 0.0897, 0.2615, 0.7149],
         [0.7814, 0.7555, 0.7151,  ..., 0.9115, 0.7646, 0.1663]],

        [[0.7998, 0.6774, 0.9741,  ..., 0.3061, 0.2049, 0.0365],
         [0.2222, 0.2923, 0.5954,  ..., 0.8394, 0.0559, 0.3342],
         [0.9677, 0.8514, 0.3461,  ..., 0.7125, 0.1140, 0.6617],
         ...,
         [0.2198, 0.6306, 0.9968,  ..., 0.4170, 0.3388, 0.7686],
         [0.0921, 0.6807, 0.7072,  ..., 0.2134, 0.2689, 0.4710],
         [0.2259, 0.0076, 0.4561,  ..., 0.4641, 0.5137, 0.3500]],

        [[0.4535, 0.7591, 0.3024,  ..., 0.1509, 0.0175, 0.7571],
         [0.9331, 0.2505, 0.5421,  ..., 0.7534, 0.2722, 0.2664],
         [0.6459, 0.3758, 0.4443,  ..., 0.5658, 0.0965, 0.

In [40]:
torch.ones(size = (1,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [41]:
torch.zeros(size = (1,4,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [43]:
zero_to_ten = torch.arange(0,10,2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [46]:
torch.zeros_like(zero_to_ten) # torch.ones_like(zero_to_ten)

tensor([0, 0, 0, 0, 0])

In [53]:
float_32_tensor = torch.rand(size=(1,2,4),dtype = None,device = None)
float_32_tensor

tensor([[[0.5868, 0.6649, 0.1559, 0.6112],
         [0.4529, 0.2443, 0.8916, 0.6496]]])

In [64]:
def show_tensor_info(tensor):
    print(tensor)
    print('Shape of the tensor : ',tensor.shape)
    print('Dtype of the tensor : ',tensor.dtype)
    print('Device tensor is stored on ',tensor.device)

In [65]:
show_tensor_info(float_32_tensor)

tensor([[[0.5868, 0.6649, 0.1559, 0.6112],
         [0.4529, 0.2443, 0.8916, 0.6496]]])
Shape of the tensor :  torch.Size([1, 2, 4])
Dtype of the tensor :  torch.float32
Device tensor is stored on  cpu


In [63]:
float_16_tensor = torch.rand(size = (1,5,8),device = 'cpu',dtype = torch.float16)

In [66]:
show_tensor_info(float_16_tensor)

tensor([[[0.7705, 0.7939, 0.4966, 0.8804, 0.2681, 0.6245, 0.3179, 0.7886],
         [0.2271, 0.5303, 0.6323, 0.7085, 0.9570, 0.5737, 0.4888, 0.2407],
         [0.4897, 0.0854, 0.9736, 0.5225, 0.0532, 0.6733, 0.1641, 0.6670],
         [0.7808, 0.4697, 0.8716, 0.1851, 0.8359, 0.0947, 0.7666, 0.2275],
         [0.4868, 0.0938, 0.1519, 0.8198, 0.0674, 0.9302, 0.2959, 0.8486]]],
       dtype=torch.float16)
Shape of the tensor :  torch.Size([1, 5, 8])
Dtype of the tensor :  torch.float16
Device tensor is stored on  cpu


## Tensor Operations 

In [88]:
tensor_a = torch.tensor([3,8,2,4,1],dtype = torch.int8,device = 'cpu')
tensor_a

tensor([3, 8, 2, 4, 1], dtype=torch.int8)

In [89]:
tensor_a.add(2)  # not an inplace operation 
tensor_a.add_(1) # inplace operation

tensor([4, 9, 3, 5, 2], dtype=torch.int8)

In [91]:
tensor_a+3

tensor([ 7, 12,  6,  8,  5], dtype=torch.int8)

In [92]:
tensor_a.sub_(3)

tensor([ 1,  6,  0,  2, -1], dtype=torch.int8)

In [94]:
tensor_a

tensor([ 1,  6,  0,  2, -1], dtype=torch.int8)

In [100]:
tensor_b = torch.tensor([4,1,2,1,0]) # element wise multiplication 

In [101]:
tensor_a*tensor_b

tensor([4, 6, 0, 2, 0])

In [124]:
tensor_c = torch.tensor([[3,1],[4,1],[0,1],[0,0],[0,1]])
tensor_c

tensor([[3, 1],
        [4, 1],
        [0, 1],
        [0, 0],
        [0, 1]])

In [127]:
tensor_b

tensor([4, 1, 2, 1, 0])

In [130]:
tensor_c.shape,tensor_b.shape

(torch.Size([5, 2]), torch.Size([5]))

In [131]:
tensor_b.matmul(tensor_c)

tensor([16,  7])

In [134]:
tensor_c.T

tensor([[3, 4, 0, 0, 0],
        [1, 1, 1, 0, 1]])

## torch.nn.Linear

In [146]:
tensor_a = torch.tensor([[1, 2],[3, 4],[5, 6]],dtype = torch.float32)
tensor_a

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [147]:
linear = torch.nn.Linear(2,6)
linear

Linear(in_features=2, out_features=6, bias=True)

In [148]:
output = linear(tensor_a)

In [149]:
output

tensor([[ 0.2307,  1.8185,  0.8033,  0.8387, -0.3663, -0.2012],
        [ 0.1191,  3.6163,  1.4421,  2.1875, -1.1498, -1.3732],
        [ 0.0076,  5.4141,  2.0809,  3.5363, -1.9333, -2.5453]],
       grad_fn=<AddmmBackward0>)

## Aggregations 

In [153]:
output.min(),output.max(),output.mean()

(tensor(-2.5453, grad_fn=<MinBackward1>),
 tensor(5.4141, grad_fn=<MaxBackward1>),
 tensor(0.8070, grad_fn=<MeanBackward0>))

In [155]:
output.argmin(),output.argmax()

(tensor(17), tensor(13))

In [160]:
output.argsort(axis = 0),output.argsort(axis =1)

(tensor([[2, 0, 0, 0, 2, 2],
         [1, 1, 1, 1, 1, 1],
         [0, 2, 2, 2, 0, 0]]),
 tensor([[4, 5, 0, 2, 3, 1],
         [5, 4, 0, 2, 3, 1],
         [5, 4, 0, 2, 3, 1]]))

## Reshaping,Stacking,Squeezing

In [163]:
tensor = torch.rand(size = (1,10))
tensor

tensor([[0.5873, 0.3549, 0.1438, 0.6859, 0.8104, 0.0905, 0.9596, 0.0146, 0.2502,
         0.5280]])

In [167]:
new_tensor = tensor.reshape(2,5)
new_tensor

tensor([[0.5873, 0.3549, 0.1438, 0.6859, 0.8104],
        [0.0905, 0.9596, 0.0146, 0.2502, 0.5280]])

In [168]:
tensor_stack = torch.rand(size = (2,5))
tensor_stack

tensor([[0.1907, 0.0787, 0.5939, 0.2674, 0.0409],
        [0.1935, 0.0553, 0.1815, 0.0040, 0.9740]])

In [189]:
torch.stack([new_tensor,tensor_stack]).shape

torch.Size([2, 2, 5])

In [182]:
x = torch.arange(1., 8.)
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [191]:
torch.stack([x,x],dim=1),torch.stack([x,x],dim=0)

(tensor([[1., 1.],
         [2., 2.],
         [3., 3.],
         [4., 4.],
         [5., 5.],
         [6., 6.],
         [7., 7.]]),
 tensor([[1., 2., 3., 4., 5., 6., 7.],
         [1., 2., 3., 4., 5., 6., 7.]]))

In [192]:
tensor_stack

tensor([[0.1907, 0.0787, 0.5939, 0.2674, 0.0409],
        [0.1935, 0.0553, 0.1815, 0.0040, 0.9740]])

In [205]:
y = torch.rand(1,1,1,1,8)
y

tensor([[[[[0.0809, 0.9738, 0.5469, 0.7175, 0.6700, 0.9263, 0.2051, 0.9990]]]]])

In [209]:
y = y.squeeze() # removing all single dimensions from a tensor 
y

tensor([0.0809, 0.9738, 0.5469, 0.7175, 0.6700, 0.9263, 0.2051, 0.9990])

In [213]:
y.unsqueeze(dim=0)

tensor([[0.0809, 0.9738, 0.5469, 0.7175, 0.6700, 0.9263, 0.2051, 0.9990]])

## Slicing tensors 

In [216]:
tensor = torch.rand(size=(4,6))
tensor

tensor([[0.4227, 0.7020, 0.5319, 0.9453, 0.5285, 0.7403],
        [0.9422, 0.3503, 0.6180, 0.6052, 0.1961, 0.8165],
        [0.3005, 0.8079, 0.6313, 0.6338, 0.9357, 0.3574],
        [0.6502, 0.4510, 0.9120, 0.5145, 0.0500, 0.4572]])

In [217]:
tensor[:,1] # first value from all the rows  

tensor([0.7020, 0.3503, 0.8079, 0.4510])

In [219]:
tensor[0,:] # all the values from zeroth row 

tensor([0.4227, 0.7020, 0.5319, 0.9453, 0.5285, 0.7403])

In [220]:
tensor[0,4]

tensor(0.5285)

In [222]:
tensor = torch.rand(size= (2,3,5))
tensor

tensor([[[0.9463, 0.8097, 0.2704, 0.3558, 0.0428],
         [0.6720, 0.8350, 0.7866, 0.2592, 0.9121],
         [0.2627, 0.8511, 0.6653, 0.8152, 0.3332]],

        [[0.4234, 0.3227, 0.8205, 0.1982, 0.0515],
         [0.0159, 0.2152, 0.0089, 0.6064, 0.5441],
         [0.5619, 0.4142, 0.1019, 0.6506, 0.0675]]])

In [232]:
tensor[:,:,1] # all the items, all the rows but only first column 

tensor([[0.8097, 0.8350, 0.8511],
        [0.3227, 0.2152, 0.4142]])

## Numpy array Conversion 

In [233]:
torch.from_numpy(np.array([1,3,5,0]))

tensor([1, 3, 5, 0], dtype=torch.int32)

In [235]:
torch_tensor = torch.tensor([0,5,5,3,5,0])
torch_tensor.numpy()

array([0, 5, 5, 3, 5, 0], dtype=int64)

##  Creating random seed 

In [238]:
torch.manual_seed(seed=19)

## Setting device type

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'