In [5]:
import torch
import torch.nn as nn

In [6]:
batch_size,token_size,embedding_size = 2,3,4

In [13]:
torch.manual_seed(101)
tensor = torch.randn(batch_size,token_size,embedding_size)

In [14]:
tensor

tensor([[[-0.6028, -0.1208, -0.4323,  1.8811],
         [-0.7158,  0.0026,  0.2056,  0.5626],
         [-1.0023, -0.5726, -0.4914, -0.2580]],

        [[-0.4303, -1.5510, -0.2353,  0.0139],
         [ 0.8110,  1.0818, -0.0259,  0.3774],
         [-0.4152, -0.7236, -1.1235,  1.7995]]])

In [25]:
torch.manual_seed(101)
layer_norm = nn.LayerNorm(embedding_size)
layer_norm

LayerNorm((4,), eps=1e-05, elementwise_affine=True)

In [40]:
layer_norm(tensor)

tensor([[[-0.7868, -0.3032, -0.6157,  1.7058],
         [-1.5639, -0.0239,  0.4113,  1.1766],
         [-1.5645,  0.0315,  0.3330,  1.2000]],

        [[ 0.2011, -1.6710,  0.5268,  0.9431],
         [ 0.5924,  1.2343, -1.3913, -0.4354],
         [-0.2641, -0.5361, -0.8888,  1.6890]]],
       grad_fn=<NativeLayerNormBackward0>)

In [27]:
layer_norm.weight

Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)

In [28]:
layer_norm.bias

Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)

In [44]:
tensor.mean(0, keepdim=True) # batch mean

tensor([[[-0.5165, -0.8359, -0.3338,  0.9475],
         [ 0.0476,  0.5422,  0.0898,  0.4700],
         [-0.7087, -0.6481, -0.8075,  0.7707]]])

In [102]:
class LayerNorm:
    def __init__(self, dim, eps=1e-5, momentum=0.1):
        self.eps = eps
        self.gamma = torch.ones(dim)
        self.beta = torch.zeros(dim)
    
    def __call__(self, x):
        # calculate the forward pass
        xmean = x.mean(2, keepdim=True) # batch mean
        xvar = x.var(2, keepdim=True) # batch variance
        xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
        self.out = self.gamma * xhat + self.beta
        return self.out
    
    def parameters(self):
        return [self.gamma, self.beta]

In [103]:
layernorm = LayerNorm(embedding_size)

In [104]:
layernorm(tensor)

(tensor([[[ 0.1813],
          [ 0.0137],
          [-0.5811]],
 
         [[-0.5507],
          [ 0.5611],
          [-0.1157]]]),
 tensor([[[-0.6814, -0.2626, -0.5333,  1.4773],
          [-1.3544, -0.0207,  0.3562,  1.0190],
          [-1.3549,  0.0273,  0.2884,  1.0393]],
 
         [[ 0.1741, -1.4472,  0.4563,  0.8168],
          [ 0.5131,  1.0689, -1.2049, -0.3771],
          [-0.2287, -0.4643, -0.7697,  1.4627]]]))

In [95]:
tensor.mean(2,keepdim=True)

tensor([[[ 0.1813],
         [ 0.0137],
         [-0.5811]],

        [[-0.5507],
         [ 0.5611],
         [-0.1157]]])

In [105]:
tensor.size(-1)

4

In [107]:
tensor.size()

torch.Size([2, 3, 4])

In [108]:
tensor.shape

torch.Size([2, 3, 4])

In [112]:
tensor.dim()

3